# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * auth_brute_force
# 
# Translators:
# Antonio Trueba, 2016
# Eduardo Rodríguez Crespo <erocre@gmail.com>, 2016
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012
# Hotellook, 2014
# Matjaž Mozetič <m.mozetic@matmoz.si>, 2015
# Paulo Ricardo <ti@shoppingescritorio.com.br>, 2016
msgid ""
msgstr ""
"Project-Id-Version: server-tools (8.0)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-12 14:33+0000\n"
"PO-Revision-Date: 2016-05-11 16:47+0000\n"
"Last-Translator: Paulo Ricardo <ti@shoppingescritorio.com.br>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/oca/OCA-server-tools-8-0/language/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#. module: auth_brute_force
#: field:res.banned.remote,active:0
msgid "Active"
msgstr "Ativo"

#. module: auth_brute_force
#: field:res.authentication.attempt,attempt_date:0
msgid "Attempt Date"
msgstr "Data da tentativa"

#. module: auth_brute_force
#: field:res.banned.remote,attempt_ids:0
msgid "Attempts"
msgstr "Tentativas"

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_authentication_attempt
#: model:ir.ui.menu,name:auth_brute_force.menu_res_authentication_attempt
msgid "Authentication Attempts"
msgstr "Tentativas de autenticação"

#. module: auth_brute_force
#: field:res.authentication.attempt,result:0
msgid "Authentication Result"
msgstr "Resultado da autenticação"

#. module: auth_brute_force
#: field:res.banned.remote,ban_date:0
msgid "Ban Date"
msgstr "Proibido Data"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:34
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Banned"
msgstr "Proibido"

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_banned_remote
#: model:ir.ui.menu,name:auth_brute_force.menu_res_banned_remote
msgid "Banned Remotes"
msgstr "Remotos proibidos"

#. module: auth_brute_force
#: field:res.authentication.attempt,create_uid:0
#: field:res.banned.remote,create_uid:0
msgid "Created by"
msgstr "Criado por"

#. module: auth_brute_force
#: field:res.authentication.attempt,create_date:0
#: field:res.banned.remote,create_date:0
msgid "Created on"
msgstr "Criado em"

#. module: auth_brute_force
#: field:res.banned.remote,description:0
msgid "Description"
msgstr "Descrição"

#. module: auth_brute_force
#: field:res.authentication.attempt,display_name:0
#: field:res.banned.remote,display_name:0
msgid "Display Name"
msgstr "Nome para Mostrar"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:33
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Failed"
msgstr "Falhou"

#. module: auth_brute_force
#: field:res.authentication.attempt,id:0 field:res.banned.remote,id:0
msgid "ID"
msgstr "Identificação"

#. module: auth_brute_force
#: field:res.authentication.attempt,__last_update:0
#: field:res.banned.remote,__last_update:0
msgid "Last Modified on"
msgstr "Última atualização em"

#. module: auth_brute_force
#: field:res.authentication.attempt,write_uid:0
#: field:res.banned.remote,write_uid:0
msgid "Last Updated by"
msgstr "Última atualização por"

#. module: auth_brute_force
#: field:res.authentication.attempt,write_date:0
#: field:res.banned.remote,write_date:0
msgid "Last Updated on"
msgstr "Última atualização em"

#. module: auth_brute_force
#: field:res.authentication.attempt,remote:0 field:res.banned.remote,remote:0
msgid "Remote ID"
msgstr "Identificação Remota"

#. module: auth_brute_force
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
msgid "Successful"
msgstr "Sucesso"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:32
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Successfull"
msgstr "Sucesso"

#. module: auth_brute_force
#: field:res.authentication.attempt,login:0
msgid "Tried Login"
msgstr "Tentativa de Login"

#. module: auth_brute_force
#: help:res.banned.remote,active:0
msgid "Uncheck this box to unban the remote"
msgstr "Desmarque esta caixa para desbloquear o remoto"

#. module: auth_brute_force
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
msgid "Without Success"
msgstr "Sem Sucesso"
